### ISSUE TITLE
Mention Blogging

### ISSUE THREAD

**Issue by RJ722** [amu-oss/whattodo#3]
Points to include:

- How to ask for invite for https://blogs.amuoss.tk?
- Always register your email so that in case you forget your password, you don't get locked out of your account.
- How to make blog public?
- How to subscribe your RSS feed in the #blog-students channel?

**Comment by roshnet** [comment]
@RJ722 I would like to take this up, please.

**Comment by RJ722** [comment]
Great @roshnet, assigned this to you!

**Comment by RJ722** [comment]
I just had this idea out of the blue, and I haven't thought about it much, so thought of documenting it here. 

---

Ideally, we can have a script which could automatically take all the usernames on https://blogs.amuoss.tk, find the link to their RSS feed and subscribe it to the #blog-students channel on Slack. What do you all think about it?

**Comment by roshnet** [comment]
@haider8 what do you say?
